import './cards/timetable-card.js'
import './cards/homework-card.js'
import './cards/grades-card.js'
import './cards/averages-card.js'
import './cards/evaluations-card.js'
import './cards/absences-card.js'
import './cards/delays-card.js'

import './editors/timetable-card-editor.js'
import './editors/homework-card-editor.js'
import './editors/grades-card-editor.js'
import './editors/evaluations-card-editor.js'
import './editors/delays-card-editor.js'
import './editors/averages-card-editor.js'
import './editors/absences-card-editor.js'