import './cards/timetable-card.js'
import './cards/homework-card.js'
import './cards/grades-card.js'
import './cards/averages-card.js'
import './cards/evaluations-card.js'
import './cards/absences-card.js'
import './cards/delays-card.js'